name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # 개인 토큰을 사용할 것인지 말 것인지
        persist-credentials: false 
    - name: 1. pip 업그래이드
      run: python -m pip install --upgrade pip
    - name: 2. 환경 설정
      run: pip install -r requirements.txt
    - name: 2.5 테스트 ifconfig
      run: ifconfig
    - name: 2.6 ping test
      run: ping -c 3 8.8.8.8
    - name: 3. 크롤링 실행
      run: python Sise_trans_style.py
    - name: Commit files
      run: |
        git config --local user.email "ggus.park@gmail.com"
        git config --local user.name "ggus.park"
        git add .
        git commit -m "Run crawler and update current data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
